#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wasteofspace"
name = "Waste of Space"
description.en = "Waste of Space, does absolutely nothing useful."
description.fr = "Waste of Space, ne fait absolument rien d'utile."

version = "1.0~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "WTFPL"
code = "https://github.com/YunoHost-Apps/wasteofspace_ynh"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wasteofspace"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/YunoHost-Apps/wasteofspace_ynh/releases/download/v1.0/assets.tar.xz"
    sha256 = "330ddcf3d0f6eea05b2945e051d06ab5f1fbf6e82f70a27d84181da0c854b9bc"

    [resources.sources.data]
    url = "https://github.com/YunoHost-Apps/wasteofspace_ynh/releases/download/v1.0/noassets.html.xz"
    sha256 = "233c3e5a9c0beeaee2ba0cee51dda17b452a57f89d80345b75fdb4a15705aba7"
    in_subdir = false
    rename = "noassets.html"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data", "config"]
    group = "www-data:r"

    [resources.permissions]
    main.url = "/"
